name: Hedgehog Sentinel EXE Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install PyPackagers
      run: pip install PyQt6 PyQt6-WebEngine pyinstaller
    - name: Build EXE Package
      run: |
        # --collect-all komutu o meşhur DLL hatalarını (icuuc vb.) kökten çözer
        pyinstaller --onedir --windowed --collect-all PyQt6 --collect-all PyQt6_WebEngine --name "Hedgehog_Sentinel" main.py
    - name: Upload Finished Pack
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Sentinel_Windows
        path: dist/Hedgehog_Sentinel/
