name: Hedgehog Firefox EXE

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Python Setup
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install
      run: pip install PyQt6 PyQt6-WebEngine pyinstaller
    - name: Build
      run: pyinstaller --onedir --windowed --collect-all PyQt6 --collect-all PyQt6_WebEngine --name "Hedgehog_Firefox" main.py
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Firefox_Windows
        path: dist/Hedgehog_Firefox/
