name: Hedgehog Firefox EXE Builder

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install PyQt5 PyQtWebEngine pyinstaller
    - name: Build EXE Folder
      run: |
        # --onedir kullanıyoruz, DLL hatalarını en aza indirir
        pyinstaller --onedir --windowed --name "Hedgehog_Sentinel" main.py
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Sentinel_Windows
        path: dist/Hedgehog_Sentinel/
