name: Hedgehog Sentinel Nuitka Build

on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - name: Install Nuitka and PyQt6
      run: pip install PyQt6 PyQt6-WebEngine nuitka
    - name: Build with Nuitka (Standalone)
      run: |
        # Bu komut kodu C++'a çevirir, DLL hatalarını bitirir
        python -m nuitka --standalone --onefile --enable-plugin=qt-plugins --windows-disable-console --output-filename=Hedgehog_Sentinel.exe main.py
    - name: Upload Nuitka EXE
      uses: actions/upload-artifact@v4
      with:
        name: Hedgehog_Sentinel_Ultimate
        path: Hedgehog_Sentinel.exe
